name: my_ufape
description: "Aplicativo auxiliar para alunos da UFAPE"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.13.0
  flutter_secure_storage: ^9.2.4
  html: ^0.15.6
  fl_chart: ^1.1.1
  auto_injector: ^2.1.1
  routefly: ^3.1.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/