name: my_ufape
description: "Aplicativo auxiliar para alunos da UFAPE"
publish_to: 'none'
version: 0.1.8

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.13.0
  flutter_secure_storage: ^9.2.4
  html: ^0.15.6
  fl_chart: ^1.1.1
  auto_injector: ^2.1.1
  routefly: ^3.1.3
  result_dart: ^2.1.1
  shared_preferences: ^2.5.3
  result_command: ^2.1.0
  brasil_fields: ^1.18.0
  # isar
  isar_community: ^3.3.0-dev.3
  isar_community_flutter_libs: ^3.3.0-dev.3
  path_provider: ^2.1.5
  calendar_view: ^1.4.0
  shorebird_code_push: ^2.0.5
  terminate_restart: ^1.0.11
  package_info_plus: ^9.0.0
  clipboard: ^2.0.2
  logarte: ^1.4.0
  share_plus: ^12.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  # isar
  isar_community_generator: ^3.3.0-dev.3
  build_runner: any
  flutter_launcher_icons: ^0.14.4
  rename_app: ^1.6.5
  flutter_native_splash: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - shorebird.yaml

  fonts:
    - family: Exo2
      fonts:
        - asset: assets/fonts/Exo2-Thin.ttf
          weight: 100
        - asset: assets/fonts/Exo2-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Exo2-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Exo2-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Exo2-Light.ttf
          weight: 300
        - asset: assets/fonts/Exo2-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Exo2-Regular.ttf
          weight: 400
        - asset: assets/fonts/Exo2-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Exo2-Medium.ttf
          weight: 500
        - asset: assets/fonts/Exo2-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Exo2-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Exo2-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Exo2-Bold.ttf
          weight: 700
        - asset: assets/fonts/Exo2-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Exo2-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Exo2-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Exo2-Black.ttf
          weight: 900
        - asset: assets/fonts/Exo2-BlackItalic.ttf
          weight: 900
          style: italic