// GENERATED FILE. PLEASE DO NOT EDIT THIS FILE!!

import 'package:flutter/widgets.dart';
import 'package:routefly/routefly.dart';

import 'ui/charts/charts_page.dart' as a0;
import 'ui/curricular_profile/curricular_profile_page.dart' as a1;
import 'ui/debug_siga/debug_siga_page.dart' as a2;
import 'ui/grades/grades_page.dart' as a3;
import 'ui/home/home_page.dart' as a4;
import 'ui/login/login_page.dart' as a5;
import 'ui/settings/settings_page.dart' as a6;
import 'ui/siga/siga_page.dart' as a7;
import 'ui/splash/splash_page.dart' as a8;
import 'ui/subjects/subjects_page.dart' as a9;
import 'ui/timetable/timetable_page.dart' as a10;

Route b0Builder(BuildContext ctx, RouteSettings settings) =>
    Routefly.defaultRouteBuilder(
      ctx,
      settings,
      const a0.ChartsPage(),
    );
Route b1Builder(BuildContext ctx, RouteSettings settings) =>
    Routefly.defaultRouteBuilder(
      ctx,
      settings,
      const a1.CurricularProfilePage(),
    );
Route b2Builder(BuildContext ctx, RouteSettings settings) =>
    Routefly.defaultRouteBuilder(
      ctx,
      settings,
      const a2.DebugSigaPage(),
    );
Route b3Builder(BuildContext ctx, RouteSettings settings) =>
    Routefly.defaultRouteBuilder(
      ctx,
      settings,
      const a3.GradesPage(),
    );
Route b4Builder(BuildContext ctx, RouteSettings settings) =>
    Routefly.defaultRouteBuilder(
      ctx,
      settings,
      const a4.HomePage(),
    );
Route b5Builder(BuildContext ctx, RouteSettings settings) =>
    Routefly.defaultRouteBuilder(
      ctx,
      settings,
      const a5.LoginPage(),
    );
Route b6Builder(BuildContext ctx, RouteSettings settings) =>
    Routefly.defaultRouteBuilder(
      ctx,
      settings,
      const a6.SettingsPage(),
    );
Route b7Builder(BuildContext ctx, RouteSettings settings) =>
    Routefly.defaultRouteBuilder(
      ctx,
      settings,
      const a7.SigaPage(),
    );
Route b8Builder(BuildContext ctx, RouteSettings settings) =>
    Routefly.defaultRouteBuilder(
      ctx,
      settings,
      const a8.SplashPage(),
    );
Route b9Builder(BuildContext ctx, RouteSettings settings) =>
    Routefly.defaultRouteBuilder(
      ctx,
      settings,
      const a9.SubjectsPage(),
    );
Route b10Builder(BuildContext ctx, RouteSettings settings) =>
    Routefly.defaultRouteBuilder(
      ctx,
      settings,
      const a10.TimetablePage(),
    );
