// GENERATED FILE. PLEASE DO NOT EDIT THIS FILE!!

part of 'app_widget.dart';

List<RouteEntity> get routes => [
      RouteEntity(
        key: '/charts',
        uri: Uri.parse('/charts'),
        routeBuilder: b0Builder,
      ),
      RouteEntity(
        key: '/curricular_profile',
        uri: Uri.parse('/curricular_profile'),
        routeBuilder: b1Builder,
      ),
      RouteEntity(
        key: '/debug_siga',
        uri: Uri.parse('/debug_siga'),
        routeBuilder: b2Builder,
      ),
      RouteEntity(
        key: '/grades',
        uri: Uri.parse('/grades'),
        routeBuilder: b3Builder,
      ),
      RouteEntity(
        key: '/home',
        uri: Uri.parse('/home'),
        routeBuilder: b4Builder,
      ),
      RouteEntity(
        key: '/login',
        uri: Uri.parse('/login'),
        routeBuilder: b5Builder,
      ),
      RouteEntity(
        key: '/settings',
        uri: Uri.parse('/settings'),
        routeBuilder: b6Builder,
      ),
      RouteEntity(
        key: '/siga',
        uri: Uri.parse('/siga'),
        routeBuilder: b7Builder,
      ),
      RouteEntity(
        key: '/splash',
        uri: Uri.parse('/splash'),
        routeBuilder: b8Builder,
      ),
      RouteEntity(
        key: '/timetable',
        uri: Uri.parse('/timetable'),
        routeBuilder: b9Builder,
      ),
    ];

const routePaths = (
  path: '/',
  charts: '/charts',
  curricularProfile: '/curricular_profile',
  debugSiga: '/debug_siga',
  grades: '/grades',
  home: '/home',
  login: '/login',
  settings: '/settings',
  siga: '/siga',
  splash: '/splash',
  timetable: '/timetable',
);
